spring.application.name=omni-contact


spring.datasource.url=jdbc:mysql://localhost:3036/omni
spring.datasource.username=root
spring.datasource.password=Nccm@110820

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
